FROM node:25.6.0-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends procps curl ffmpeg \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /home/node/app

RUN mkdir -p /tmp/streamtube-videos \
    && chown node:node /tmp/streamtube-videos

USER node

CMD [ "tail", "-f", "/dev/null" ]
